###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.8'

services:
    mysql:
        container_name: "mysql.local"
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASS}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '${DB_PORT:-3306}:3306'
        networks:
            - core

    webserver:
        container_name: "webserver.local"
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${APP_PORT:-80}:80'
        networks:
            - core

    php-fpm:
        container_name: "fpm.local"
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        networks:
            - core

networks:
  core:
    driver: bridge
